"""
Deterministic, verifiable game bank for self-play.

Every game is generated by MY code and its ground-truth answer is computed by
MY code — never by evaluating model output. The verifier only compares a
model's stated answer string against the known answer. No LLM is the judge.

Games come in one registry (GAME_TYPES, rotation order) and each returns
(question, answer, kind). Kinds carry an answer "shape" so the verifier can
compare appropriately: numeric, fraction, word, boolean, or matrix-cell.
"""

import math
import random
import re

# ─────────────────────────── helpers ───────────────────────────

def _r(lo, hi):
    return random.randint(lo, hi)


def _pick(xs):
    return random.choice(xs)


# ─────────────────────────── 1. arithmetic ───────────────────────────

def gen_arithmetic():
    a, b = _r(2, 24), _r(2, 24)
    op = _pick(["+", "-", "*"])
    if op == "+":
        ans = a + b
    elif op == "-":
        if a < b:
            a, b = b, a
        ans = a - b
    else:
        ans = a * b
    return f"Compute exactly, no steps: {a} {op} {b}", str(ans), "arithmetic"


# ─────────────────────────── 2. algebra ───────────────────────────

def gen_algebra():
    x = _r(-20, 20)
    a = _pick([2, 3, 4, 5, 7])
    b = _r(-30, 30)
    c = a * x + b
    return f"Solve for x (integer): {a}x + {b} = {c}", str(x), "algebra"


# ─────────────────────────── 3. syllogism ───────────────────────────

SYLLOGISMS = [
    ("All ravens are birds. All birds have feathers.", "All ravens have feathers.", True),
    ("All ravens are birds. Some birds are black.", "Some ravens are black.", False),
    ("No fish can fly. All salmon are fish.", "No salmon can fly.", True),
    ("All pianos are instruments. Some instruments are heavy.", "All pianos are heavy.", False),
    ("All embers glow. All that glows is warm.", "All embers are warm.", True),
    ("Some birds are black. Some black things are shiny.", "Some birds are shiny.", False),
]


def gen_syllogism():
    prem, concl, valid = _pick(SYLLOGISMS)
    ans = "VALID" if valid else "INVALID"
    q = (f"Premises: {prem} Conclusion: {concl} "
         f"Is the conclusion logically VALID or INVALID? Answer VALID or INVALID.")
    return q, ans, "syllogism"


# ─────────────────────────── 4. code output ───────────────────────────

def gen_code():
    kind = _pick(["triple", "square", "shift", "mod"])
    n = _r(1, 30)
    if kind == "triple":
        code, val = "def f(n):\n    return n * 3 + 1", n * 3 + 1
    elif kind == "square":
        code, val = "def f(n):\n    return n * n - n", n * n - n
    elif kind == "shift":
        code, val = "def f(n):\n    return (n + 4) // 2", (n + 4) // 2
    else:
        code, val = "def f(n):\n    return n % 7", n % 7
    q = f"Given this Python function:\n{code}\n\nWhat does f({n}) return? Answer with just the integer."
    return q, str(val), "code"


# ─────────────────────────── 5. modular arithmetic ───────────────────────────

def gen_modular():
    m = _r(5, 13)
    x = _r(20, 200)
    return f"What is {x} mod {m}?", str(x % m), "modular"


# ─────────────────────────── 6. percentages ───────────────────────────

def gen_percentage():
    p = _pick([10, 20, 25, 50, 75])
    ans = _r(5, 80)
    n = ans * 100 // p
    return f"What is {p}% of {n}?", str(ans), "percentage"


# ─────────────────────────── 7. fractions ───────────────────────────

FRACTIONS = [
    ("1/2", "1/3", "5/6"),
    ("1/2", "1/4", "3/4"),
    ("1/3", "1/6", "1/2"),
    ("1/2", "1/8", "5/8"),
    ("1/4", "1/8", "3/8"),
    ("2/3", "1/6", "5/6"),
    ("1/5", "1/10", "3/10"),
    ("3/4", "1/8", "7/8"),
]


def gen_fraction():
    a, b, ans = _pick(FRACTIONS)
    return f"Compute and give the reduced fraction: {a} + {b}", ans, "fraction"


# ─────────────────────────── 8. number sequences ───────────────────────────

def gen_sequence():
    kind = _pick(["arith", "geom", "square", "cube"])
    if kind == "arith":
        s, d = _r(1, 9), _r(2, 9)
        terms = [s + i * d for i in range(4)]
        ans = s + 4 * d
    elif kind == "geom":
        s, r = _r(1, 5), _r(2, 4)
        terms = [s * r ** i for i in range(4)]
        ans = s * r ** 4
    elif kind == "square":
        n = _r(2, 9)
        terms = [i * i for i in range(n, n + 4)]
        ans = (n + 4) ** 2
    else:
        n = _r(2, 6)
        terms = [i ** 3 for i in range(n, n + 4)]
        ans = (n + 4) ** 3
    return f"Next term: {', '.join(map(str, terms))}, ?", str(ans), "sequence"


# ─────────────────────────── 9. combinatorics ───────────────────────────

def gen_combinatorics():
    if _pick([True, False]):
        n = _r(3, 7)
        return f"How many ways to arrange {n} distinct objects in a row?", str(math.factorial(n)), "combinatorics"
    n = _r(3, 9)
    k = _r(2, min(4, n - 1))
    return f"How many ways to choose {k} items from {n} (order doesn't matter)?", str(math.comb(n, k)), "combinatorics"


# ─────────────────────────── 10. probability ───────────────────────────

PROB = [
    ("A fair coin is flipped twice. What is the probability of exactly one head?", "1/2"),
    ("A fair coin is flipped twice. What is the probability of two heads?", "1/4"),
    ("Two fair dice are rolled. What is the probability the sum is 7?", "1/6"),
    ("A fair six-sided die is rolled. What is the probability of rolling a 6?", "1/6"),
    ("A fair coin is flipped twice. What is the probability of at least one head?", "3/4"),
    ("Two fair dice are rolled. What is the probability the sum is 12?", "1/36"),
]


def gen_probability():
    q, ans = _pick(PROB)
    return q + " Give the reduced fraction.", ans, "probability"


# ─────────────────────────── 11. base conversion ───────────────────────────

def gen_base():
    if _pick([True, False]):
        n = _r(3, 15)
        return f"Convert binary {bin(n)[2:]} to decimal.", str(n), "base"
    n = _r(3, 63)
    return f"Convert decimal {n} to binary.", bin(n)[2:], "base"


# ─────────────────────────── 12. Caesar cipher ───────────────────────────

CAESAR_WORDS = ["CAT", "DOG", "HELLO", "WORLD", "FIRE", "EMBER", "CLOUD", "TIGER", "STONE", "LIGHT"]


def gen_caesar():
    w = _pick(CAESAR_WORDS)
    s = _r(1, 5)
    enc = "".join(chr((ord(c) - 65 + s) % 26 + 65) for c in w)
    return f"Decrypt this Caesar cipher (shift {s}): {enc}", w.lower(), "caesar"


# ─────────────────────────── 13. anagram ───────────────────────────

ANAGRAMS = ["WATER", "STONE", "CLOUD", "TIGER", "EMBER", "LIGHT", "HEART", "MUSIC", "RIVER", "PLANT"]


def gen_anagram():
    w = _pick(ANAGRAMS)
    letters = list(w)
    random.shuffle(letters)
    shuffled = "".join(letters)
    if shuffled == w:
        shuffled = w[::-1]
    return f"Unscramble the letters to make a word: {shuffled}", w.lower(), "anagram"


# ─────────────────────────── 14. analogy ───────────────────────────

ANALOGIES = [
    ("cat", "kitten", "dog", "puppy"),
    ("bird", "nest", "bee", "hive"),
    ("hand", "glove", "foot", "sock"),
    ("hot", "cold", "big", "small"),
    ("teacher", "school", "doctor", "hospital"),
    ("fish", "water", "bird", "air"),
    ("author", "book", "painter", "painting"),
]


def gen_analogy():
    a, b, c, d = _pick(ANALOGIES)
    return f"Complete the analogy: {a} is to {b} as {c} is to ?", d, "analogy"


# ─────────────────────────── 15. boolean logic ───────────────────────────

_BOOL_EXPRS = [
    ("(a and b) or c", "(A AND B) OR C"),
    ("(a or b) and c", "(A OR B) AND C"),
    ("(a and b) or (not c)", "(A AND B) OR (NOT C)"),
    ("a or (b and c)", "A OR (B AND C)"),
    ("(a or c) and (not b)", "(A OR C) AND (NOT B)"),
]


def gen_boolean():
    a, b, c = _pick([True, False]), _pick([True, False]), _pick([True, False])
    py, disp = _pick(_BOOL_EXPRS)
    val = eval(py, {"a": a, "b": b, "c": c})  # literal template, restricted namespace — never model text
    tf = lambda v: "T" if v else "F"
    q = f"Evaluate {disp} with A={tf(a)}, B={tf(b)}, C={tf(c)}. Answer true or false."
    return q, "true" if val else "false", "boolean"


# ─────────────────────────── 16. truth-teller / liar ───────────────────────────

TRUTH_PUZZLES = [
    ('A says: "I am the liar." Exactly one of A and B always lies. Who is the liar?', "A"),
    ('A says: "At least one of us is lying." Exactly one of A and B always lies. Who is the liar?', "B"),
]


def gen_truth_liar():
    q, ans = _pick(TRUTH_PUZZLES)
    return q, ans.lower(), "truth_liar"


# ─────────────────────────── 17. matrix Nash equilibrium ───────────────────────────

def _pure_ne(payoffs):
    """Pure-strategy Nash equilibria of a 2x2 game. payoffs[(r,c)] = (row, col)."""
    nes = []
    for r in (0, 1):
        for c in (0, 1):
            rp, cp = payoffs[(r, c)]
            row_ok = rp >= payoffs[(1 - r, c)][0]
            col_ok = cp >= payoffs[(r, 1 - c)][1]
            if row_ok and col_ok:
                nes.append((r, c))
    return nes


def gen_matrix_nash():
    for _ in range(300):
        payoffs = {(r, c): (_r(0, 9), _r(0, 9)) for r in (0, 1) for c in (0, 1)}
        nes = _pure_ne(payoffs)
        if len(nes) == 1:
            r, c = nes[0]
            rows = ["Top", "Bottom"]
            cols = ["Left", "Right"]
            matrix = (
                "Payoff matrix (row player's payoff, column player's payoff):\n"
                f"            Left           Right\n"
                f"Top     {payoffs[(0, 0)]}   {payoffs[(0, 1)]}\n"
                f"Bottom  {payoffs[(1, 0)]}   {payoffs[(1, 1)]}\n"
            )
            ans = f"{rows[r]}, {cols[c]}"
            q = (matrix + "Which cell is the (unique) pure-strategy Nash equilibrium? "
                 "Answer e.g. 'Top, Left'.")
            return q, ans.lower(), "matrix_nash"
    # unreachable in practice; fall back to a known-unique game
    return gen_matrix_nash()


def gen_matrix_play():
    """A true adversarial game: A picks a row, B picks a column, simultaneously.

    Returns a full game dict (game_type='play') — no single 'expected' answer;
    the verifier scores best-responses and whether the joint move is the
    unique pure Nash equilibrium."""
    for _ in range(300):
        payoffs = {(r, c): (_r(0, 9), _r(0, 9)) for r in (0, 1) for c in (0, 1)}
        nes = _pure_ne(payoffs)
        if len(nes) == 1:
            matrix_text = (
                "Payoff matrix (row player's payoff, column player's payoff):\n"
                f"            Left           Right\n"
                f"Top     {payoffs[(0, 0)]}   {payoffs[(0, 1)]}\n"
                f"Bottom  {payoffs[(1, 0)]}   {payoffs[(1, 1)]}\n"
            )
            return {
                "kind": "matrix_play",
                "game_type": "play",
                "pattern": "play",
                "question": matrix_text,
                "matrix_text": matrix_text,
                "payoffs": payoffs,
                "ne": nes[0],
                "rows": ["Top", "Bottom"],
                "cols": ["Left", "Right"],
                "answer": None,
            }
    return gen_matrix_play()


# ─────────────────────────── 18. prisoner's dilemma ───────────────────────────

def gen_prisoner():
    q = ("Prisoner's Dilemma: each player can Cooperate or Defect; defecting yields a "
         "better payoff than cooperating regardless of the other's choice. What is the "
         "dominant strategy for a self-interested player? Answer 'Cooperate' or 'Defect'.")
    return q, "defect", "prisoner"


# ─────────────────────────── 19. ultimatum game ───────────────────────────

def gen_ultimatum():
    q = ("Ultimatum game: a proposer offers a whole-dollar split of $100 to a responder, "
         "who can accept (both keep the split) or reject (both get nothing). Assume both "
         "are perfectly rational and the responder accepts any positive amount. What offer "
         "($) does the subgame-perfect equilibrium predict? Answer a whole number.")
    return q, "1", "ultimatum"


# ─────────────────────────── 20. word problems ───────────────────────────

_WORD_TEMPLATES = [
    ("Tom has {a} apples, buys {b} more, then gives {c} away. How many does he have left?",
     lambda a, b, c: a + b - c),
    ("A train has {a} passengers; {b} get on and {c} get off. How many passengers now?",
     lambda a, b, c: a + b - c),
    ("A box holds {a} marbles and each bag adds {b}. If there are {c} bags, how many marbles in total?",
     lambda a, b, c: a + b * c),
]


def gen_word_math():
    tpl, fn = _pick(_WORD_TEMPLATES)
    a, b, c = _r(3, 20), _r(2, 15), _r(1, 10)
    if fn(0, 0, 0) is None:
        pass
    ans = fn(a, b, c)
    if ans < 0:  # keep it positive and sensible
        a, c = c, a
        ans = fn(a, b, c)
    return tpl.format(a=a, b=b, c=c), str(ans), "word_math"


# ─────────────────────────── 21. dilemmas (no ground truth) ───────────────────────────

# Dilemmas have no deterministic correct answer, so they can't go through the
# numeric verifier. Two flavors:
#   insight — a false dilemma with a hidden third option; we detect whether the
#             agent ESCAPED the binary (proposed something beyond the two horns).
#   moral   — a genuine value conflict with no right answer; always judged by
#             the paid reflection step.

DILEMMAS = [
    {
        "id": "trolley",
        "flavor": "insight",
        "question": ("A runaway trolley is heading for five people tied to the track. You stand at "
                     "a lever that would switch it to a side track where one person is tied. Pull the "
                     "lever: one dies. Do nothing: five die. But that's a false dilemma — there is a "
                     "third option the framing hides. What is it?"),
        "horns": [
            ("pull lever", ["lever", "pull", "switch", "side track", "kill one", "one person"]),
            ("do nothing", ["nothing", "five", "let them", "let the five", "do not pull", "don't pull"]),
        ],
        "escape_keywords": ["loop", "connect", "circle", "rejoin", "tie", "reroute", "reverse",
                            "derail", "save everyone", "save all", "save them all", "all six",
                            "both", "neither", "refuse", "untie", "free them", "step off",
                            "they can move", "third", "another way"],
    },
    {
        "id": "two_guards",
        "flavor": "insight",
        "question": ("Two doors: one leads to freedom, the other to death. Two guards: one always "
                     "tells the truth, one always lies — you don't know which is which. You may ask "
                     "one guard one yes/no question. What do you ask to find the safe door?"),
        "horns": [
            ("ask which door", ["which door", "which one", "is this", "point", "this door"]),
        ],
        "escape_keywords": ["other guard", "would say", "what would", "opposite", "other one", "if i asked"],
    },
    {
        "id": "footbridge",
        "flavor": "moral",
        "question": ("A trolley is heading for five people tied to the track. You're on a footbridge "
                     "above it, next to a large stranger; pushing him onto the track would stop the "
                     "trolley and save the five, but kill him. Do you push?"),
        "horns": [
            ("push", ["push", "yes", "sacrifice", "kill the stranger"]),
            ("don't push", ["no", "won't", "would not", "wouldn't", "do not push", "dont push"]),
        ],
        "escape_keywords": [],
    },
    {
        "id": "steal_bread",
        "flavor": "moral",
        "question": ("Your family is starving and you have no money. The baker's window is unlocked. "
                     "Do you steal a loaf of bread to feed them?"),
        "horns": [
            ("steal", ["steal", "yes", "take the bread"]),
            ("don't steal", ["no", "won't", "would not", "wouldn't", "do not steal", "dont steal"]),
        ],
        "escape_keywords": [],
    },
    {
        "id": "lifeboat",
        "flavor": "insight",
        "question": ("A lifeboat is overcrowded and taking on water. The officer says one person must "
                     "be thrown overboard or everyone drowns. But that's a false dilemma — the framing "
                     "hides a third option. What is it?"),
        "horns": [
            ("throw overboard", ["throw", "overboard", "sacrifice", "one person", "pick someone"]),
            ("accept death", ["nothing", "everyone drown", "let them", "all die"]),
        ],
        "escape_keywords": ["bail", "pump", "patch", "plug", "ration", "cargo", "supplies", "jettison",
                            "wait", "rescue", "signal", "flare", "nobody", "no one", "everyone",
                            "all of us", "both", "neither", "third", "another way"],
    },
    {
        "id": "self_sacrifice",
        "flavor": "insight",
        "question": ("A trolley is heading for five people tied to the track. You're standing beside "
                     "the track; the only lever would divert it onto one person. But there's a third "
                     "option the framing hides. What is it?"),
        "horns": [
            ("pull lever", ["lever", "pull", "switch", "one person", "side track"]),
            ("do nothing", ["nothing", "five", "let them"]),
        ],
        "escape_keywords": ["myself", "my body", "jump", "sacrifice myself", "throw myself", "derail",
                            "my own life", "self", "third", "another way", "untie", "free them"],
    },
    {
        "id": "heinz",
        "flavor": "moral",
        "question": ("Heinz's wife is dying; a druggist invented a cure but charges ten times what it "
                     "costs to make. Heinz has raised half. The druggist won't lower the price or take "
                     "payments. Should Heinz break in and steal the drug to save his wife?"),
        "horns": [
            ("steal", ["steal", "break in", "take the drug", "yes"]),
            ("don't steal", ["no", "won't", "would not", "wouldn't", "should not"]),
        ],
        "escape_keywords": [],
    },
    {
        "id": "transplant",
        "flavor": "moral",
        "question": ("Five patients need different organ transplants or they'll die. A healthy stranger "
                     "walks in for a checkup and is a perfect match for all five. Should the surgeon kill "
                     "the stranger and harvest the organs to save five?"),
        "horns": [
            ("harvest", ["kill", "harvest", "sacrifice", "operate", "take the organs", "yes"]),
            ("don't", ["no", "won't", "would not", "wouldn't", "refuse"]),
        ],
        "escape_keywords": [],
    },
    {
        "id": "timebomb",
        "flavor": "moral",
        "question": ("A bomb is set to go off in a city; a captured suspect knows where it is but won't "
                     "talk. Is it right to torture the suspect to force the location and save thousands?"),
        "horns": [
            ("torture", ["torture", "force", "beat", "waterboard", "yes"]),
            ("don't torture", ["no", "won't", "would not", "wouldn't", "refuse"]),
        ],
        "escape_keywords": [],
    },
    {
        "id": "shallow_pond",
        "flavor": "moral",
        "question": ("You're on your way to a life-changing job interview in a new suit. A child is "
                     "drowning in a shallow pond right beside you. Saving them would ruin the suit and "
                     "cost you the job. Do you save the child?"),
        "horns": [
            ("save", ["save", "rescue", "help", "jump in", "yes"]),
            ("don't save", ["no", "won't", "would not", "wouldn't", "ignore", "walk away"]),
        ],
        "escape_keywords": [],
    },
]


def gen_dilemma():
    d = _pick(DILEMMAS)
    return {
        "question": d["question"],
        "answer": None,
        "kind": "dilemma",
        "pattern": "moral",
        "flavor": d["flavor"],
        "horns": d["horns"],
        "escape_keywords": d["escape_keywords"],
    }


# ─────────────────────────── 22. computation (wave 1) ───────────────────────────

def gen_prime_factorization():
    primes = [2, 3, 5, 7, 11, 13]
    factors = [random.choice(primes) for _ in range(random.randint(2, 4))]
    factors.sort()
    n = 1
    for f in factors:
        n *= f
    q = f"Factor {n} into primes. List the prime factors in ascending order (e.g. 2 2 3)."
    return q, " ".join(map(str, factors)), "prime_factorization"


def gen_gcd_lcm():
    if random.choice([True, False]):
        a, b = random.randint(2, 60), random.randint(2, 60)
        return f"What is the greatest common divisor (GCD) of {a} and {b}?", str(math.gcd(a, b)), "gcd_lcm"
    a, b = random.randint(2, 12), random.randint(2, 12)
    return f"What is the least common multiple (LCM) of {a} and {b}?", str(a * b // math.gcd(a, b)), "gcd_lcm"


def gen_linear_equation():
    x = random.randint(-10, 10)
    a = random.randint(1, 4)
    c = random.randint(1, 3)
    if a == c:
        a += 1
    b = random.randint(-15, 15)
    d = (a - c) * x + b
    q = f"Solve for x (integer): {a}x + {b} = {c}x + {d}"
    return q, str(x), "linear_equation"


def gen_inequality():
    a = random.choice([2, 3, 4, 5])
    b = random.randint(-10, 10)
    c = random.randint(-10, 10)
    x_min = (c - b) // a + 1
    q = f"What is the smallest integer x such that {a}x + {b} > {c}?"
    return q, str(x_min), "inequality"


def gen_geometry():
    kind = random.choice(["rect", "tri", "hyp"])
    if kind == "rect":
        w, h = random.randint(3, 12), random.randint(3, 12)
        return f"What is the area of a rectangle with width {w} and height {h}?", str(w * h), "geometry"
    if kind == "tri":
        b, h = random.randint(2, 12), random.choice([2, 4, 6, 8, 10])
        return f"What is the area of a triangle with base {b} and height {h}?", str(b * h // 2), "geometry"
    k = random.randint(2, 6)
    return f"A right triangle has legs {3 * k} and {4 * k}. What is the length of the hypotenuse?", str(5 * k), "geometry"


DAYS = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]


def gen_calendar():
    start = random.randint(0, 6)
    offset = random.randint(1, 60)
    end = (start + offset) % 7
    q = f"If today is {DAYS[start].title()}, what day of the week is it {offset} days from now?"
    return q, DAYS[end], "calendar"


def gen_optimization():
    a, b = random.randint(1, 5), random.randint(1, 5)
    c, d = random.randint(1, 3), random.randint(1, 3)
    n = random.randint(4, 10)
    best = -1
    for x in range(n + 1):
        for y in range(n + 1):
            if c * x + d * y <= n:
                best = max(best, a * x + b * y)
    q = (f"Maximize {a}x + {b}y subject to {c}x + {d}y ≤ {n}, with x, y ≥ 0 integers. "
         f"What is the maximum value of {a}x + {b}y?")
    return q, str(best), "optimization"


CONSTRAINT_PUZZLES = [
    ("Alice, Bob, and Carol each own exactly one of a cat, a dog, and a bird. Alice does not own the dog. Bob owns the bird. What pet does Carol own?", "dog"),
    ("X, Y, and Z each wear a different color: red, blue, or green. X wears red. Z does not wear blue. What color does Y wear?", "blue"),
    ("Dana, Erin, and Frank finish a race in 1st, 2nd, and 3rd place. Dana did not finish 1st. Erin finished 2nd. Who finished 3rd?", "dana"),
]


def gen_constraint():
    q, ans = random.choice(CONSTRAINT_PUZZLES)
    return q, ans, "constraint"


def _bfs_dist(edges, n, a, b):
    adj = {i: [] for i in range(n)}
    for u, v in edges:
        adj[u].append(v)
        adj[v].append(u)
    seen = {a}
    frontier = [a]
    dist = 0
    while frontier:
        nxt = []
        for u in frontier:
            if u == b:
                return dist
            for v in adj[u]:
                if v not in seen:
                    seen.add(v)
                    nxt.append(v)
        frontier = nxt
        dist += 1
    return -1


def gen_graph():
    n = random.randint(5, 7)
    edges = set()
    for i in range(n):
        for j in range(i + 1, n):
            if random.random() < 0.35:
                edges.add((i, j))
    for i in range(n - 1):
        edges.add((i, i + 1))
    edge_str = ", ".join(f"{u}-{v}" for u, v in sorted(edges))
    if random.choice([True, False]):
        a = random.randint(0, n - 1)
        b = random.choice([x for x in range(n) if x != a])
        dist = _bfs_dist(edges, n, a, b)
        q = (f"Nodes 0..{n - 1} with undirected edges: {edge_str}. "
             f"What is the shortest path length (number of edges) from node {a} to node {b}?")
        return q, str(dist), "graph"
    node = random.randint(0, n - 1)
    deg = sum(1 for e in edges if node in e)
    q = f"Nodes 0..{n - 1} with undirected edges: {edge_str}. What is the degree of node {node}?"
    return q, str(deg), "graph"


def gen_recurrence():
    kind = random.choice(["linear", "fib", "geo"])
    n = random.randint(4, 8)
    if kind == "linear":
        a0 = random.randint(0, 3)
        k = random.randint(2, 5)
        seq = [a0]
        for _ in range(n):
            seq.append(seq[-1] * k + 1)
        q = f"A sequence is defined by a(0)={a0} and a(n) = {k}*a(n-1) + 1. What is a({n})?"
        return q, str(seq[n]), "recurrence"
    if kind == "fib":
        seq = [0, 1]
        while len(seq) <= n + 1:
            seq.append(seq[-1] + seq[-2])
        q = f"A Fibonacci-like sequence starts a(0)=0, a(1)=1, a(n)=a(n-1)+a(n-2). What is a({n})?"
        return q, str(seq[n]), "recurrence"
    a0 = random.randint(1, 3)
    r = random.randint(2, 3)
    q = f"A sequence has a(0)={a0} and each term is {r} times the previous term. What is a({n})?"
    return q, str(a0 * r ** n), "recurrence"


# ─────────────────────────── registry (rotation order) ───────────────────────────

GAME_TYPES = [
    ("arithmetic", gen_arithmetic),
    ("algebra", gen_algebra),
    ("syllogism", gen_syllogism),
    ("code", gen_code),
    ("modular", gen_modular),
    ("percentage", gen_percentage),
    ("fraction", gen_fraction),
    ("sequence", gen_sequence),
    ("combinatorics", gen_combinatorics),
    ("probability", gen_probability),
    ("base", gen_base),
    ("caesar", gen_caesar),
    ("anagram", gen_anagram),
    ("analogy", gen_analogy),
    ("boolean", gen_boolean),
    ("truth_liar", gen_truth_liar),
    ("matrix_nash", gen_matrix_nash),
    ("matrix_play", gen_matrix_play),
    ("prisoner", gen_prisoner),
    ("ultimatum", gen_ultimatum),
    ("word_math", gen_word_math),
    ("prime_factorization", gen_prime_factorization),
    ("gcd_lcm", gen_gcd_lcm),
    ("linear_equation", gen_linear_equation),
    ("inequality", gen_inequality),
    ("geometry", gen_geometry),
    ("calendar", gen_calendar),
    ("optimization", gen_optimization),
    ("constraint", gen_constraint),
    ("graph", gen_graph),
    ("recurrence", gen_recurrence),
    ("dilemma", gen_dilemma),
]

_GENS = dict(GAME_TYPES)


def list_games():
    return [k for k, _ in GAME_TYPES]


def gen_question(kind=None, rng=None):
    """Generate a game. kind=None -> random; else use the named generator."""
    r = rng or random
    if kind is None:
        kind, _ = r.choice(GAME_TYPES)
    if kind in ("dilemma", "matrix_play"):
        return _GENS[kind]()  # these return full game dicts directly
    gen = _GENS[kind]
    q, answer, k = gen()
    return {"question": q, "answer": answer, "kind": k, "pattern": "solve"}


# ─────────────────────────── grading ───────────────────────────

def _norm(s):
    if s is None:
        return ""
    return s.strip().lower().replace(",", "").replace("`", "").replace("'", "")


def parse_answer(text):
    """Pull a value + confidence out of a model's structured reply."""
    ans = None
    conf = None
    m = re.search(r"(?im)^\s*answer\s*:\s*(.+)$", text or "")
    if m:
        ans = m.group(1).strip()
    c = re.search(r"(?im)^\s*confidence\s*:\s*([0-9]*\.?[0-9]+)", text or "")
    if c:
        try:
            conf = float(c.group(1))
        except ValueError:
            conf = None
    if ans is None:
        ans = (text or "").strip()
    return ans, (conf if conf is not None else 0.5)


_WORD_KINDS = frozenset([
    "caesar", "anagram", "analogy", "truth_liar", "prisoner",
    "syllogism", "boolean", "calendar", "constraint",
])

# Leading articles / filler a lenient word-matcher should ignore when deciding
# whether the model restated the expected answer.
_ARTICLES = frozenset(["the", "a", "an", "it", "is", "that"])


def _tokens(s):
    """Lowercased word tokens (letters/digits only), articles stripped."""
    toks = re.findall(r"[a-z0-9]+", s)
    return [t for t in toks if t not in _ARTICLES]


def _word_match(a, e):
    """Lenient word-level match: expected's key tokens must appear in answer.

    Handles "The dog" vs "dog", "Carol owns the cat" vs "cat", "it is blue" vs
    "blue" — but NOT a genuinely different word ("Carol owns the cat" vs "dog"
    stays wrong, because the expected token is absent).
    """
    et = _tokens(e)
    if not et:
        return False
    at = _tokens(a)
    if not at:
        return False
    # all expected content tokens must show up somewhere in the answer
    for tok in et:
        if tok not in at:
            return False
    return True


def check_correct(answer_text, expected, kind=None):
    """Deterministic, kind-aware, LENIENT grade.

    The strict-equality failures from the overnight run were mostly the grader's
    fault: "The dog" vs "dog", "it is blue" vs "blue" were marked wrong purely
    on phrasing. This matcher is semantic/lenient: word kinds match on key-token
    presence, numeric kinds on extracted numbers, fractions via Fraction. It never
    marks a genuinely different answer correct (a missing expected token => False).
    """
    a = _norm(answer_text)
    e = _norm(expected)
    if not a:
        return False

    # matrix Nash — match the row,column cell, ignoring filler
    if kind == "matrix_nash":
        ac = re.findall(r"top|bottom", a)
        cc = re.findall(r"left|right", a)
        ec = re.findall(r"top|bottom", e)
        fc = re.findall(r"left|right", e)
        if not ec or not fc:
            return _word_match(a, e)
        return bool(ac and cc and ac[0] == ec[0] and cc[0] == fc[0])

    if kind in ("fraction", "probability"):
        try:
            af = _parse_frac(a)
            ef = _parse_frac(e)
            if af is not None and ef is not None:
                return af == ef
        except Exception:
            pass
        return _word_match(a, e)

    if kind in _WORD_KINDS:
        return _word_match(a, e)

    if kind == "prime_factorization":
        a_nums = sorted(int(x) for x in re.findall(r"\d+", a))
        e_nums = sorted(int(x) for x in re.findall(r"\d+", e))
        return a_nums == e_nums and bool(a_nums)

    # numeric kinds (algebra, code, modular, arithmetic, sequence, gcd_lcm, ...)
    a_num = re.sub(r"[^0-9-]", "", a)
    e_num = re.sub(r"[^0-9-]", "", e)
    if e_num and a_num == e_num:
        return True
    # fall back to word match for letter answers that slipped through
    return _word_match(a, e)


def _parse_frac(s):
    """Parse 'a/b' or 'a' or '0.5' to a Fraction (or None)."""
    from fractions import Fraction
    s = s.strip()
    if "/" in s:
        return Fraction(s)
    if s.replace(".", "", 1).isdigit():
        return Fraction(s)
    return None


def verify(agent_answer, game):
    """Return a grade dict for one agent. `game` is the dict from gen_question."""
    ans_text, conf = parse_answer(agent_answer)
    kind = game["kind"]
    if kind == "dilemma":
        a = _norm(ans_text)
        horn_hits = {}
        for label, kws in game.get("horns", []):
            horn_hits[label] = sum(1 for kw in kws if kw in a)
        escape_hits = sum(1 for kw in game.get("escape_keywords", []) if kw in a)
        # Escaped = the agent reached for a concept beyond the two offered horns.
        # (escape keywords are specific multi-word phrases like "save everyone",
        #  so a plain horn answer like "pull the lever" won't trigger them.)
        escaped = escape_hits > 0
        return {
            "answer": ans_text,
            "confidence": conf,
            "correct": None,
            "escaped": escaped,
            "horn_hits": horn_hits,
            "escape_hits": escape_hits,
        }
    correct = check_correct(ans_text, game["answer"], kind)
    return {
        "answer": ans_text,
        "confidence": conf,
        "correct": correct,
        "expected": game["answer"],
    }


def parse_move(text, options):
    """Return the index of the first `options` label found in text, else None."""
    t = _norm(text) if text else ""
    for i, opt in enumerate(options):
        if opt in t:
            return i
    return None


def grade_matrix_play(game, a_idx, b_idx):
    """Grade a simultaneous-move 2x2 game. a_idx/b_idx are row/col indices."""
    payoffs = game["payoffs"]
    rows, cols = game["rows"], game["cols"]
    rp, cp = payoffs[(a_idx, b_idx)]
    a_best = rp >= payoffs[(1 - a_idx, b_idx)][0]
    b_best = cp >= payoffs[(a_idx, 1 - b_idx)][1]
    ne = game["ne"]
    equilibrium = (a_idx, b_idx) == ne
    return {
        "row_move": rows[a_idx],
        "col_move": cols[b_idx],
        "payoff_row": rp,
        "payoff_col": cp,
        "a_best_response": a_best,
        "b_best_response": b_best,
        "equilibrium": equilibrium,
        "ne": f"{rows[ne[0]]}, {cols[ne[1]]}",
    }
